title: "VidarDB"
url: https://www.vidardb.com # site url
baseurl: "" # apply repo name if use it under gh-pages branch

repo: https://github.com/vidardb/vidardb
comments: false

plugins:
  - jekyll-last-modified-at
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-babel
  - jekyll-github-metadata
  - bourbon
  - neat

collections:
  basic-syntax:
  extended-syntax:
  tools:
    output: true
    permalink: /tools/:title/

defaults:
  - scope:
      type: tools
    values:
      layout: tool

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Author settings
author:
  name : "soarpenguin"

# social settings
og_locale: "en_US"

kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids:       true
  toc_levels:     1..3

exclude: ["vendor", "Gemfile", "Gemfile.lock", "README.md", "LICENSE.txt", "Rakefile"]
